### ISSUE TITLE
looks buggy on iOS7

### ISSUE THREAD

**Issue by oriSomething** [gulpjs/gulpjs.github.io#21]
![gulp-ios7](https://cloud.githubusercontent.com/assets/2685242/5591165/bb1d6482-9155-11e4-81a2-b669a7f8b40a.png)

it's a little bit horrible to inspect it with the safari inspector. so i can't say for sure what cause it. maybe when i'll download iOS simulator for iOS 7 it would be easier.
but my guess it's related to a buggy behavior of the `vh` / `vw` units.

**Comment by contra** [comment]
Ah yeah those units will probably do that. I'll give it a check. Max-height needs to be added to the logo, max-width added to the text, and maybe a viewport addition needs to be added.

**Comment by oriSomething** [comment]
hey, i don't know stylus, but this is my little fix. it's a hack because it doesn't deal with small screens in landscape mode (which is another issue). which need some code changes (not using absolute positioning + transforms in small screen).
anyway, for iOS safari 7 in portrait mode it did the job
```css
.main-header-content {
  width: 90vw;
}

.main-header-text {
  margin-left: auto;
  margin-right: auto;
  max-width: 100%;
}

@media only screen and (max-width: 480px) {
  .logo {
    max-width: 25%;
  }
}
```
